import 'dotenv/config';
import { z } from 'zod';

const envSchema = z
  .object({
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    PORT: z.string().default('4000'),
    DATABASE_URL: z.string().url(),
    REDIS_URL: z.string().url(),
    JWT_ACCESS_SECRET: z.string().min(16),
    JWT_REFRESH_SECRET: z.string().min(16),
    ACCESS_TOKEN_TTL: z.string().default('15m'),
    REFRESH_TOKEN_TTL: z.string().default('7d'),
    COOKIE_DOMAIN: z.string().default('localhost'),
    CORS_ORIGINS: z.string().default(''),
    LOG_LEVEL: z.string().default('info'),
    JWT_ISSUER: z.string().optional(),
    JWT_AUDIENCE: z.string().optional(),
    CSRF_COOKIE_NAME: z.string().default('csrfToken'),
    HLS_ENABLED: z.string().default('false'),
    HLS_OUTPUT_DIR: z.string().default('./hls'),
    HLS_PUBLIC_BASE_URL: z.string().optional(),
    HLS_AUDIO_BITRATE_KBPS: z.string().default('16'),
    HLS_SEGMENT_SECONDS: z.string().default('1'),
    HLS_RTMP_PUBLISH_URL_TEMPLATE: z.string().optional(),
    HLS_RTMP_PLAY_URL_TEMPLATE: z.string().optional(),
    HLS_SIGNING_SECRET: z.string().optional(),
    HLS_URL_TTL_SECONDS: z.string().default('900'),
    HLS_FFMPEG_MODE: z.enum(['local', 'docker']).default('local'),
    HLS_FFMPEG_DOCKER_IMAGE: z.string().default('jrottenberg/ffmpeg:6.1-alpine'),
    HLS_FFMPEG_DOCKER_NETWORK: z.string().optional(),
    HLS_FFMPEG_CONTAINER_PREFIX: z.string().default('ffmpeg-hls-'),
    GOOGLE_CLIENT_ID: z.string().optional(),
    BROADCAST_MAX_MINUTES: z.string().default('15'),
    BROADCAST_PREP_MINUTES: z.string().default('2'),
    SCHEDULER_INTERVAL_SECONDS: z.string().default('60'),
    LIVEKIT_URL: z.string().url().optional(),
    LIVEKIT_API_KEY: z.string().optional(),
    LIVEKIT_API_SECRET: z.string().optional(),
    FCM_SERVICE_ACCOUNT_JSON: z.string().optional(),
    APNS_KEY: z.string().optional(),
    APNS_KEY_ID: z.string().optional(),
    APNS_TEAM_ID: z.string().optional(),
    APNS_VOIP_BUNDLE_ID: z.string().optional(),
    APNS_PRODUCTION: z.string().default('false'),
    SEED_SUPER_ADMIN_EMAIL: z.string().email().optional(),
    SEED_SUPER_ADMIN_PASSWORD: z.string().min(8).optional(),
  })
  .transform((raw) => ({
    ...raw,
    PORT: Number(raw.PORT),
    BROADCAST_MAX_MINUTES: Number(raw.BROADCAST_MAX_MINUTES),
    BROADCAST_PREP_MINUTES: Number(raw.BROADCAST_PREP_MINUTES),
    SCHEDULER_INTERVAL_SECONDS: Number(raw.SCHEDULER_INTERVAL_SECONDS),
    APNS_PRODUCTION: raw.APNS_PRODUCTION === 'true',
    HLS_ENABLED: raw.HLS_ENABLED === 'true',
    HLS_AUDIO_BITRATE_KBPS: Number(raw.HLS_AUDIO_BITRATE_KBPS),
    HLS_SEGMENT_SECONDS: Number(raw.HLS_SEGMENT_SECONDS),
    HLS_URL_TTL_SECONDS: Number(raw.HLS_URL_TTL_SECONDS),
  }));

export const env = envSchema.parse(process.env);
